application: mycourse  # FIXME: Replace this with your application id
version: 1
runtime: python27
api_version: 1
threadsafe: false

instance_class: F1

env_variables:
  GCB_PRODUCT_VERSION: '1.9.0'

  # Enable collection of stats on numbers of calls to the datastore,
  # memcache, and email-sending backends.  Used for profiling CourseBuilder
  # to improve performance.  See
  # https://cloud.google.com/appengine/docs/python/tools/appstats
  GCB_APPSTATS_ENABLED: false

  GCB_REGISTERED_MODULES:
    modules.dashboard.dashboard
    modules.activity_tag.activity_tag
    modules.admin.admin
    modules.announcements.announcements
    modules.assessment_tags.questions
    modules.balancer.balancer
    modules.code_tags.code_tags
    modules.core_tags.core_tags
    modules.course_explorer.course_explorer
    modules.courses.courses
    modules.analytics.analytics
    modules.certificate.certificate
    modules.data_pump.data_pump
    modules.data_removal.data_removal
    modules.embed.embed
    modules.extra_tabs.extra_tabs
    modules.i18n_dashboard.i18n_dashboard
    modules.invitation.invitation
    modules.manual_progress.manual_progress
    modules.mapreduce.mapreduce_module
    modules.math.math
    modules.notifications.notifications
    modules.oeditor.oeditor
    modules.questionnaire.questionnaire
    modules.rating.rating
    modules.review.review
    modules.search.search
    modules.skill_map.skill_map
    modules.unsubscribe.unsubscribe
    modules.upload.upload
    modules.usage_reporting.usage_reporting
    modules.gitkit.gitkit=disabled
    modules.oauth2.oauth2=disabled


includes:
- custom.yaml

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
- name: PIL
  version: "1.1.7"
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
- url: /cron/.*
  script: main.app
  login: admin
  secure: always
- url: /mapreduce/worker/.*
  script: main.app
  login: admin
  secure: always
- url: /.*
  script: main.app
  secure: always

skip_files:
# GAE default patterns.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# CB-specific patterns.
- ^internal/.*$
